-- 코드를 작성해주세요
WITH YEARLY_SCORE AS (
    SELECT
        G.EMP_NO,
        SUM(G.SCORE) AS SCORE
    FROM HR_GRADE G
    WHERE G.YEAR = 2022
    GROUP BY G.EMP_NO
),
MAX_SCORE AS (
    SELECT MAX(SCORE) AS MAX_SCORE
    FROM YEARLY_SCORE
)
SELECT
    Y.SCORE AS SCORE,
    E.EMP_NO AS EMP_NO,
    E.EMP_NAME AS EMP_NAME,
    E.POSITION AS POSITION,
    E.EMAIL AS EMAIL
FROM YEARLY_SCORE Y
JOIN MAX_SCORE M ON Y.SCORE = M.MAX_SCORE
JOIN HR_EMPLOYEES E ON E.EMP_NO = Y.EMP_NO;